port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ""
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
    - 8.8.8.8
    - 1.0.0.1
    - https://dns.google/dns-query
  fallback:
    - 1.1.1.1
    - 8.8.4.4
    - https://cloudflare-dns.com/dns-query
    - 112.215.203.254
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
    - 112.215.203.254
proxies:
  - name: graph.instagram.com
    type: vmess
    server: bz.kmnetz.com
    port: 443
    uuid: e20b387c-e6d2-457e-b326-cdb5af7a14ca
    alterId: 0
    cipher: auto
    udp: true
    tls: true
    skip-cert-verify: true
    servername: graph.instagram.com
    network: ws
    ws-opts:
      path: /netzvmess
      headers:
        Host: graph.instagram.com
  - name: g.whatsapp.net
    type: vmess
    server: bz.kmnetz.com
    port: 443
    uuid: e20b387c-e6d2-457e-b326-cdb5af7a14ca
    alterId: 0
    cipher: auto
    udp: true
    tls: true
    skip-cert-verify: true
    servername: bz.kmnetz.com
    network: ws
    ws-opts:
      path: /netzvmess
      headers:
        Host: bz.kmnetz.com
  - name: 104.17.238.25
    type: vmess
    server: 104.17.238.25
    port: 443
    uuid: e20b387c-e6d2-457e-b326-cdb5af7a14ca
    alterId: 0
    cipher: auto
    udp: true
    tls: true
    skip-cert-verify: true
    servername: bz.kmnetz.com
    network: ws
    ws-opts:
      path: /netzvmess
      headers:
        Host: bz.kmnetz.com
  - name: 104.21.28.78
    type: vmess
    server: 104.21.28.78
    port: 443
    uuid: e20b387c-e6d2-457e-b326-cdb5af7a14ca
    alterId: 0
    cipher: auto
    udp: true
    tls: true
    skip-cert-verify: true
    servername: bz.kmnetz.com
    network: ws
    ws-opts:
      path: /netzvmess
      headers:
        Host: bz.kmnetz.com
  - name: investor.fb.com
    type: vmess
    server: investor.fb.com
    port: 443
    uuid: e20b387c-e6d2-457e-b326-cdb5af7a14ca
    alterId: 0
    cipher: auto
    udp: true
    tls: true
    skip-cert-verify: true
    servername: bz.kmnetz.com
    network: ws
    ws-opts:
      path: /netzvmess
      headers:
        Host: bz.kmnetz.com
  - name: app-stg.gopay.co.id
    type: vmess
    server: app-stg.gopay.co.id
    port: 443
    uuid: e20b387c-e6d2-457e-b326-cdb5af7a14ca
    alterId: 0
    cipher: auto
    udp: true
    tls: true
    skip-cert-verify: true
    servername: bz.kmnetz.com
    network: ws
    ws-opts:
      path: /netzvmess
      headers:
        Host: bz.kmnetz.com
proxy-groups:
  - name: Rama_Server
    type: select
    proxies:
      - graph.instagram.com
      - g.whatsapp.net
      - 104.17.238.25
      - 104.21.28.78
      - investor.fb.com
      - app-stg.gopay.co.id
      - DIRECT
rules:
  - MATCH,Rama_Server